/*
 * Copyright 2002-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.web.socket.adapter;

import java.lang.reflect.Field;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import org.junit.jupiter.api.Test;

import org.springframework.util.IdGenerator;
import org.springframework.util.JdkIdGenerator;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Regression tests for CVE-2026-41838 at the 5.3.39 baseline.
 *
 * <p>WebSocket session IDs were generated by {@code AlternativeJdkIdGenerator}, which seeds a
 * plain {@link java.util.Random} — a 48-bit linear congruential generator — from eight
 * SecureRandom bytes once, and then derives every subsequent id from that generator. An
 * observer who sees enough ids can recover the 48-bit state and predict the rest, so session
 * ids are not cryptographically unpredictable. {@code JdkIdGenerator} delegates to
 * {@link UUID#randomUUID()}, which draws from a {@code SecureRandom} for every id.
 *
 * <p>The first test is structural on purpose: which generator is installed IS the remedy, and
 * the predictability of {@code java.util.Random} is a documented property of the JDK class
 * rather than something worth re-deriving here.
 *
 * @see <a href="https://spring.io/security/cve-2026-41838">CVE-2026-41838</a>
 */
class AbstractWebSocketSessionIdGeneratorTests {

	private static IdGenerator installedGenerator() throws Exception {
		Field field = AbstractWebSocketSession.class.getDeclaredField("idGenerator");
		field.setAccessible(true);
		return (IdGenerator) field.get(null);
	}

	@Test
	void sessionIdsComeFromASecureRandomBackedGenerator() throws Exception {
		assertThat(installedGenerator()).isInstanceOf(JdkIdGenerator.class);
	}

	@Test
	void generatedIdsRemainUniqueAndWellFormed() throws Exception {
		IdGenerator generator = installedGenerator();
		Set<UUID> ids = new HashSet<>();
		for (int i = 0; i < 1000; i++) {
			UUID id = generator.generateId();
			assertThat(id).isNotNull();
			assertThat(ids.add(id)).as("duplicate id at iteration %d", i).isTrue();
		}
	}

}
